---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: docker.io/library/postgres:17.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          containerPort: 5432
        envFrom:
        - configMapRef:
            name: database-env
        - secretRef:
            name: database-secrets
      terminationGracePeriodSeconds: 180