---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: consumer:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: consumer-env
      terminationGracePeriodSeconds: 180